set(TRAJECTORY_SIZE "100" CACHE STRING "Size of trajectory")
set(INT_STEPS "10" CACHE STRING "Number of integration steps between consecutive trajectory points")
set(MIN_DIST "0.02" CACHE STRING "Min. allowed distance between missiles and planets")

set(POT_TYPE "2D" CACHE STRING "Type of potential")
set(POT_TYPE_VALUES "2D" "3D")
set_property(CACHE POT_TYPE PROPERTY STRINGS ${POT_TYPE_VALUES})
list(FIND POT_TYPE_VALUES ${POT_TYPE} POT_TYPE_INDEX)
if(${POT_TYPE_INDEX} EQUAL -1)
    message(FATAL_ERROR "Unkown potential type '${POT_TYPE}'; supported entries are ${POT_TYPE_VALUES}")
endif()

if("${POT_TYPE}" STREQUAL "3D")
    set(N_POT "2" CACHE STRING "Approximation order of potential")
else()
    set(N_POT "???")
endif()

set(COMPOSITION_SCHEME "p8s15" CACHE STRING "Composition method of integrator")
set_property(CACHE COMPOSITION_SCHEME PROPERTY STRINGS "p2s1" "p4s3" "p4s5" "p6s9" "p8s15")
if("${COMPOSITION_SCHEME}" STREQUAL "p2s1")
    set(COMPOSITION_ID "0")
    set(COMPOSITION_STAGES "1")
elseif("${COMPOSITION_SCHEME}" STREQUAL "p4s3")
    set(COMPOSITION_ID "1")
    set(COMPOSITION_STAGES "3")
elseif("${COMPOSITION_SCHEME}" STREQUAL "p4s5")
    set(COMPOSITION_ID "2")
    set(COMPOSITION_STAGES "5")
elseif("${COMPOSITION_SCHEME}" STREQUAL "p6s9")
    set(COMPOSITION_ID "3")
    set(COMPOSITION_STAGES "9")
elseif("${COMPOSITION_SCHEME}" STREQUAL "p8s15")
    set(COMPOSITION_ID "4")
    set(COMPOSITION_STAGES "15")
else()
    message(FATAL_ERROR "Unkown composition method '${COMPOSITION_SCHEME}'")
endif()