name: Build docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      shell: bash
      run: sudo apt-get install doxygen graphviz

    - name: Install python dependencies
      shell: bash
      run: |
        sudo apt-get install python3-pip && \
        pip3 install --user pytest && \
        pip3 install --user numpy && \
        pip3 install --user sphinx && \
        pip3 install --user sphinx-rtd-theme

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_DOXYGEN=ON

    - name: Build main documentation
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install main documentation 
      shell: bash
      run: cp -r ${{github.workspace}}/build/html/ ${{github.workspace}}/docs/

    - name: Build Python binding documentation
      shell: bash
      working-directory: bindings/python/doc
      run: make html

    - name: Install Python binding documentation 
      shell: bash
      run: |
        cp -r ${{github.workspace}}/bindings/python/doc/build/ ${{github.workspace}}/docs/py-bindings/ && \
        touch ${{github.workspace}}/docs/.nojekyll

    - name: Commit files
      run: |
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git checkout -b ghaction-doc
         git add --force ${{github.workspace}}/docs/
         git commit -m "Update documentation" -a

    - name: Push changes
      run: git push --force -u origin ghaction-doc
