name: Continuous Integration

on:
  push:
    branches:
    - main
    - development

  pull_request:
    branches:
    - main
    - development

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update -q
        && sudo apt-get install clang-format black -q -y

    - name: Check formatting of C library
      run: cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake

    - name: Check formatting of Python binding
      run: black --check bindings/python/{src,test}

  test:
    needs: [lint]

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        pot_type: [2D, 3D]

    steps:
    - uses: actions/checkout@v3

    - name: Install Catch2 and Python dependencies
      run: sudo apt-get update -q
        && sudo apt-get install catch2 python3-pip -q -y
        && pip3 install --user pytest
        && pip3 install --user numpy

    - name: Configure
      env: { CC: clang }
      run: cmake --preset=ci-sanitize -DPOT_TYPE=${{ matrix.pot_type }}

    - name: Build
      run: cmake --build build/sanitize -j 2

    - name: Test C library
      working-directory: build/sanitize
      env:
        ASAN_OPTIONS: "strict_string_checks=1:\
                       detect_stack_use_after_return=1:\
                       check_initialization_order=1:\
                       strict_init_order=1:\
                       detect_leaks=1"
        UBSAN_OPTIONS: print_stacktrace=1
      run: ctest --output-on-failure -j 2

    - name: Test Python binding
      run: mkdir -p bindings/python/lib/
        && ln -sfr build/sanitize/libgravix2.so bindings/python/lib/
        && python3 -m pytest bindings/python/test/
